eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: ${ENABLE_EUREKA:true}
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
# spring:
#   zipkin:
#     baseUrl: http://zipkin-svc:9411
